apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
      - name: todo-app-frontend
        image: dilbag463/todo-app-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
      - name: todo-app-frontend
        image: dilbag463/todo-app-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-service
spec:
  type: NodePort
  selector:
    app: todo-app-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
